import { Hanken_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Header/Navbar";
import Footer from "@/components/Footer/Footer";

const HankenGrotesk = Hanken_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

 
  return (
    <html lang="en">
      <body className="antialiased bg-bg px-6 md:px-52 text-accent box-border">
       <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
